### ISSUE TITLE
真机调试运行结果和 demo 表现不一致，真机调试异常

### ISSUE THREAD

**Issue by ZangTengfei** [wechat-miniprogram/awesome-skyline#1]
无法进行分段半屏，半屏组件整体上移

![image](https://github.com/wechat-miniprogram/awesome-skyline/assets/16444563/8463e397-4caa-473c-aa96-25ff662c10c8)

**Comment by linesoft2** [comment]
调试里切换成Skyline渲染试一下？

**Comment by ZangTengfei** [comment]
好吧，原来还有一个开关，现在正常了。感谢！
