### ISSUE TITLE
通讯录示例效果，无法同时支持 skyline 和 webview 渲染模式

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/awesome-skyline#4]
skyline 和 webview 各自都可以实现，但无法同时支持。

原因是 sticky-header 在 webview 模式下式，无法设置样式，也就无法兼容了

**Comment by seasonhuang** [comment]
@xiaweiss 是设置什么样 css

**Comment by seasonhuang** [comment]
@xiaweiss 更新了一版，webview 也对齐
